NodeVersion="14.15.1"
compressedNodeModulesFile="node_modules.tar.gz"
OperationId="|9SIFKJs63Ws=.4eb7efa6_"
SourceDirectoryInBuildContainer="/tmp/8d9149f9eb88d8f"
PlatformName="nodejs"
CompressDestinationDir="false"
